### ISSUE TITLE
0.1.4 release should be 0.2.4 ?

### ISSUE THREAD

**Issue by hiragram** [awslabs/smithy-swift#414]
Currently 0.2.3 is treated as latest release.

**Comment by hiragram** [comment]
@wooj2 Can you help me please?

**Comment by wooj2** [comment]
Disclaimer: I am speaking on behalf of myself.  I am not speaking on behalf of Amazon, AWS, or my current employer.

@hiragram - 
Yes, I would agree that the versioning seems a bit off for smithy-swift:
https://github.com/awslabs/smithy-swift/releases

I'm guessing that the release on 3/22/2022 for `smithy-swift` should have been 0.2.4 instead of 0.1.4.  Furthermore, looking at the latest release for aws-sdk-swift, it seems to reference 0.2.3 for ClientRuntime:
https://github.com/awslabs/aws-sdk-swift/blob/release/0.2.4/Package.swift#L313

As for a workaround (without making a new release): it seems that you could checkout these repositories locally and update the `Package.swift` files to use `package(path:)` , but this doesn't seem like a long term solution.

I think to resolve this, it seems that what is needed is:
1.  A new release of smithy-swift (ClientRuntime) with a version number higher than 0.2.3
2. A new release of aws-sdk-swift which targets this newly released version of smithy-swift(ClientRuntime)

I am pinging @atierian , as he is the one who last made a release in this repository.

**Comment by hiragram** [comment]
@wooj2 Thank you for your help! 
Making a new release as 0.2.4 should be the best and correct solution I think.

**Comment by atierian** [comment]
The 0.1.4 release was an intentional and necessary patch on the previous minor (0.1). There is a matching AWS SDK Swift 0.1.4 release as well.

The latest release being a previous minor shouldn't adversely affect any dependency managers. Are you experiencing any issues because of this?

**Comment by hiragram** [comment]
I am using v0.2.3 via AWS SDK Swift and I am using Swift 5.6

Swift 5.6 does not look supported without this patch https://github.com/awslabs/smithy-swift/pull/413/files

**Comment by atierian** [comment]
Swift 5.6 support was added to v0.2.3 as well. [[release notes](https://github.com/awslabs/smithy-swift/releases/tag/0.2.3)]
AWS SDK Swift v0.2.3 depends on Smithy Swift v0.2.3, and supports Swift 5.6

I'm closing this as it doesn't appear to be an issue. If you feel otherwise, please comment on here and I'll take a look / re-open if necessary.
