### ISSUE TITLE
Fix Xcode support by removing Packages.swift from Packages folder

### ISSUE THREAD

**Issue by brennanMKE** [awslabs/smithy-swift#421]
When working in Xcode the contents of Packages are hidden because it contains `Package.swift`. The purpose of it is not known yet it does cause difficulties when working with this package.

**Comment by ganeshnj** [comment]
By default AWSClientRuntime and Packages directories are not shown when taking a dependency on the any AWS SDK because of nested Package.swift file. 

* https://github.com/awslabs/smithy-swift/blob/main/Packages/Package.swift
* https://github.com/awslabs/aws-sdk-swift/blob/main/AWSClientRuntime/Package.swift

Delete above files, close XCode and re-open you will see AWSClientRuntime and Package dirs.

<img width="621" alt="image" src="https://user-images.githubusercontent.com/8882380/188208650-b4e7dac1-5796-4818-9950-e0a3f4877760.png">


This creates frustrating developer experience. Ideally we want below Package.swift only swift package files

* https://github.com/awslabs/smithy-swift/blob/main/Package.swift
* https://github.com/awslabs/aws-sdk-swift/blob/main/Package.swift
